firstnum = int(input("Enter an integer between 10 and 100:"))
secondnum = int(input("Enter an integer lesss than 4:"))
print(f"You entered {firstnum} and {secondnum}")
print(f"{firstnum} + {secondnum} = {firstnum + secondnum}")
print(f"{firstnum} * {secondnum} = {firstnum * secondnum}")
print(f"{firstnum} ** {secondnum} = {firstnum**secondnum}")
print(f"{firstnum} % {secondnum} = {firstnum % secondnum}")
